/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multipart-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MultipartUploadController_listMultipartUploads"];
        put?: never;
        post: operations["MultipartUploadController_startMultipartUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/multipart-upload/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["MultipartUploadController_uploadMultipartUpload"];
        post?: never;
        delete: operations["MultipartUploadController_abortMultipartUpload"];
        options?: never;
        head?: never;
        patch: operations["MultipartUploadController_completeMultipartUpload"];
        trace?: never;
    };
    "/sensor-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SensorDataController_listSensorData"];
        put?: never;
        post: operations["SensorDataController_uploadSensorDataFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sensor-data/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SensorDataController_getSensorData"];
        put?: never;
        post?: never;
        delete: operations["SensorDataController_deleteSensorData"];
        options?: never;
        head?: never;
        patch: operations["SensorDataController_updateSensorData"];
        trace?: never;
    };
    "/sensor-data/{id}/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SensorDataController_getSensorDataPresignedUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rate-limit/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RateLimitController_testRateLimit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserRequest: {
            /** @description ユーザー名 */
            name: string;
            /**
             * @description プラン
             * @enum {string}
             */
            plan: "guest" | "trial" | "basic" | "pro" | "admin" | "developer";
        };
        CreateUserResponse: {
            /** @description ユーザーID */
            id: string;
            /** @description ユーザー名 */
            name: string;
            /**
             * @description プラン
             * @enum {string}
             */
            plan: "guest" | "trial" | "basic" | "pro" | "admin" | "developer";
        };
        GetUserResponse: {
            /** @description ユーザーID */
            id: string;
            /** @description ユーザー名 */
            name: string;
            /**
             * @description プラン
             * @enum {string}
             */
            plan: "guest" | "trial" | "basic" | "pro" | "admin" | "developer";
            /**
             * Format: date-time
             * @description 登録日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        GetPlanResponse: {
            /**
             * @description プラン
             * @enum {string}
             */
            plan: "guest" | "trial" | "basic" | "pro" | "admin" | "developer";
        };
        MultiPartUpload: {
            /** @description センサデータのアップロードID */
            uploadId: string;
            /** @description センサデータ名 */
            dataName: string;
            /**
             * @description ステータス
             * @enum {string}
             */
            status: "in_progress" | "completed" | "aborted";
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        ListMultipartUploadResponse: {
            /** @description センサデータアップロード一覧 */
            multipartUploads: components["schemas"]["MultiPartUpload"][];
        };
        StartMultipartUploadRequest: {
            /** @description センサデータ名 */
            dataName: string;
        };
        StartMultipartUploadResponse: {
            /** @description センサデータのアップロードID */
            uploadId: string;
            /** @description センサデータ名 */
            dataName: string;
        };
        PostMultipartUploadResponse: {
            /** @description センサデータのアップロードID */
            uploadId: string;
            /** @description センサデータ名 */
            dataName: string;
        };
        CompleteMultipartUploadResponse: {
            /** @description センサデータのアップロードID */
            uploadId: string;
            /** @description センサデータ名 */
            dataName: string;
        };
        AbortMultipartUploadResponse: {
            /** @description センサデータのアップロードID */
            uploadId: string;
            /** @description センサデータ名 */
            dataName: string;
        };
        SensorData: {
            /** @description センサデータID */
            id: string;
            /** @description センサデータ名 */
            dataName: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        ListSensorDataResponse: {
            /** @description センサデータ一覧 */
            sensorData: components["schemas"]["SensorData"][];
        };
        UploadSensorDataRequest: {
            /** @description センサデータ名 */
            dataName: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
        };
        GetSensorDataResponse: {
            /** @description センサデータID */
            id: string;
            /** @description センサデータ名 */
            dataName: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        UpdateSensorDataRequest: {
            /** @description センサデータ名 */
            dataName: string;
        };
        UpdateSensorDataResponse: {
            /** @description センサデータID */
            id: string;
            /** @description センサデータ名 */
            dataName: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
        };
        GetSensorDataPresignedUrlResponse: {
            /** @description センサデータID */
            id: string;
            /** @description センサデータ名 */
            dataName: string;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt: string;
            /** @description presigned URL */
            presignedUrl: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserResponse"];
                };
            };
        };
    };
    UsersController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserResponse"];
                };
            };
        };
    };
    UsersController_getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPlanResponse"];
                };
            };
        };
    };
    MultipartUploadController_listMultipartUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMultipartUploadResponse"];
                };
            };
        };
    };
    MultipartUploadController_startMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartMultipartUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartMultipartUploadResponse"];
                };
            };
        };
    };
    MultipartUploadController_uploadMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        /** @description CSVデータ */
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostMultipartUploadResponse"];
                };
            };
        };
    };
    MultipartUploadController_abortMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbortMultipartUploadResponse"];
                };
            };
        };
    };
    MultipartUploadController_completeMultipartUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteMultipartUploadResponse"];
                };
            };
        };
    };
    SensorDataController_listSensorData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ページ番号 */
                page: number;
                /** @description 1ページあたりの件数 */
                perPage: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSensorDataResponse"];
                };
            };
        };
    };
    SensorDataController_uploadSensorDataFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadSensorDataRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SensorDataController_getSensorData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSensorDataResponse"];
                };
            };
        };
    };
    SensorDataController_deleteSensorData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SensorDataController_updateSensorData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSensorDataRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateSensorDataResponse"];
                };
            };
        };
    };
    SensorDataController_getSensorDataPresignedUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSensorDataPresignedUrlResponse"];
                };
            };
        };
    };
    RateLimitController_testRateLimit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
}
